<?php require_once __DIR__ . '/../config/db.php'; ensure_admin();
if($_SERVER['REQUEST_METHOD']==='POST' && !validate_csrf_token($_POST['csrf_token'] ?? null)){ http_response_code(419); exit('Invalid CSRF token'); }
if(isset($_GET['approve_volunteer'])){ if(!validate_csrf_token($_GET['csrf_token'] ?? null)){ http_response_code(419); exit('Invalid CSRF token'); } $pdo->prepare('UPDATE volunteers SET approval_status="approved" WHERE id=?')->execute([(int)$_GET['approve_volunteer']]); header('Location: /admin/index.php'); exit; }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['assign_case'])){ $pdo->prepare('UPDATE complaints SET assigned_to=?, status="in_progress" WHERE id=?')->execute([(int)$_POST['volunteer_id'], (int)$_POST['complaint_id']]); }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['create_event'])){ $pdo->prepare('INSERT INTO events(event_type,title,description,event_date,location) VALUES(?,?,?,?,?)')->execute([$_POST['event_type'],$_POST['title'],$_POST['description'],$_POST['event_date'],$_POST['location']]); }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['create_alert'])){ $pdo->prepare('INSERT INTO fraud_alerts(title,message,severity,is_active) VALUES(?,?,?,1)')->execute([trim($_POST['title']),trim($_POST['message']),trim($_POST['severity'])]); }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['create_admin'])){ if(!is_super_admin_logged_in()){ http_response_code(403); exit('Only super admin can create admins'); } $pdo->prepare('INSERT INTO admin(name,email,password_hash,role) VALUES(?,?,?,?)')->execute([trim($_POST['name']), trim($_POST['email']), password_hash($_POST['password'], PASSWORD_BCRYPT), trim($_POST['role'])==='super_admin'?'super_admin':'admin']); }

$complaints=$pdo->query('SELECT * FROM complaints ORDER BY id DESC')->fetchAll();
$pending=$pdo->query('SELECT * FROM volunteers WHERE approval_status="pending"')->fetchAll();
$approved=$pdo->query('SELECT * FROM volunteers WHERE approval_status="approved"')->fetchAll();
$qcount=(int)$pdo->query('SELECT COUNT(*) FROM quiz_questions')->fetchColumn();
$users=(int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();
$events=(int)$pdo->query('SELECT COUNT(*) FROM events')->fetchColumn();
$alerts=$pdo->query('SELECT * FROM fraud_alerts ORDER BY id DESC LIMIT 10')->fetchAll();
$admins=$pdo->query('SELECT id,name,email,role FROM admin ORDER BY id DESC')->fetchAll();
$emails=$pdo->query('SELECT * FROM email_logs ORDER BY id DESC LIMIT 10')->fetchAll();
$leaderboard=$pdo->query('SELECT participant_name,MAX(score) as score FROM quiz_results GROUP BY participant_name ORDER BY score DESC LIMIT 10')->fetchAll();
include __DIR__ . '/../includes/header.php'; ?>
<div class="container py-4"><div class="wp-shell">
<aside class="wp-sidebar p-3">
<h5 class="mb-3">Cyber Sathi Admin</h5>
<a class="d-block text-white mb-2" href="#dashboard">Dashboard</a><a class="d-block text-white mb-2" href="#users">Users</a><a class="d-block text-white mb-2" href="#volunteers">Volunteers</a><a class="d-block text-white mb-2" href="#complaints">Complaints</a><a class="d-block text-white mb-2" href="#alerts">Fraud Alerts</a><a class="d-block text-white mb-2" href="#quiz">Quiz Management</a><a class="d-block text-white mb-2" href="#results">Quiz Results</a><a class="d-block text-white mb-2" href="#certificates">Certificates</a><a class="d-block text-white mb-2" href="#leaderboard">Leaderboard</a><a class="d-block text-white mb-2" href="#phones">Fraud Phone DB</a><a class="d-block text-white mb-2" href="#checker">Fake Website Checker</a><a class="d-block text-white mb-2" href="#courses">Courses</a><a class="d-block text-white mb-2" href="#email">Email Communication</a><a class="d-block text-white mb-2" href="#media">Media</a><a class="d-block text-white mb-2" href="#settings">Settings</a>
<hr class="text-white-50"><small class="text-white-50">Logged in as <?= e($_SESSION['admin_name'] ?? 'Admin') ?></small><span class="badge bg-info text-dark mt-2"><?= e($_SESSION['admin_role'] ?? 'admin') ?></span><a class="btn btn-sm btn-outline-light mt-3" href="/admin/logout.php">Logout</a>
</aside>
<section class="wp-main p-4">
<h2 id="dashboard">Dashboard</h2>
<div class="row g-3 mb-4"><div class="col-md-2"><div class="card p-3"><strong><?= $users ?></strong><span>Total Users</span></div></div><div class="col-md-2"><div class="card p-3"><strong><?= count($complaints) ?></strong><span>Total Complaints</span></div></div><div class="col-md-2"><div class="card p-3"><strong><?= count($approved) ?></strong><span>Active Volunteers</span></div></div><div class="col-md-2"><div class="card p-3"><strong><?= (int)$pdo->query('SELECT COUNT(*) FROM quiz_results')->fetchColumn() ?></strong><span>Quiz Participants</span></div></div><div class="col-md-2"><div class="card p-3"><strong><?= (int)$pdo->query('SELECT COUNT(*) FROM quiz_results')->fetchColumn() ?></strong><span>Certificates</span></div></div><div class="col-md-2"><div class="card p-3"><strong><?= (int)$pdo->query('SELECT COUNT(*) FROM fraud_alerts WHERE is_active=1')->fetchColumn() ?></strong><span>Fraud Alerts</span></div></div></div>

<h4 id="volunteers">Approve Volunteers</h4><?php foreach($pending as $p): ?><div class="card p-2 mb-2"><?= e($p['name']) ?> (<?= e($p['email']) ?>) <a class="btn btn-sm btn-success" href="?approve_volunteer=<?= (int)$p['id'] ?>&csrf_token=<?= e(csrf_token()) ?>">Approve</a></div><?php endforeach; ?>
<h4 id="complaints" class="mt-4">Assign Complaints</h4><form method="post" class="row g-2"><?= csrf_input() ?><input type="hidden" name="assign_case" value="1"><div class="col-md-5"><select name="complaint_id" class="form-select"><?php foreach($complaints as $c): ?><option value="<?= (int)$c['id'] ?>">#<?= (int)$c['id'] ?> <?= e($c['user_name']) ?> - <?= e($c['fraud_type']) ?></option><?php endforeach; ?></select></div><div class="col-md-5"><select name="volunteer_id" class="form-select"><?php foreach($approved as $v): ?><option value="<?= (int)$v['id'] ?>"><?= e($v['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Assign</button></div></form>

<h4 id="alerts" class="mt-4">Live Fraud Alert System</h4><form method="post" class="row g-2"><?= csrf_input() ?><input type="hidden" name="create_alert" value="1"><div class="col-md-3"><input name="title" class="form-control" placeholder="Alert Title" required></div><div class="col-md-5"><input name="message" class="form-control" placeholder="Alert message" required></div><div class="col-md-2"><select name="severity" class="form-select"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><div class="col-md-2"><button class="btn btn-danger w-100">Publish</button></div></form><?php foreach($alerts as $a): ?><div class="card p-2 mt-2">[<?= e($a['severity']) ?>] <?= e($a['title']) ?> - <?= e($a['message']) ?></div><?php endforeach; ?>

<h4 id="email" class="mt-4">Email Communication (PHPMailer)</h4><form method="post" action="/api/send_email.php" class="row g-2"><?= csrf_input() ?><div class="col-md-3"><select name="recipient_type" class="form-select"><option value="single">Single User</option><option value="users">Bulk Users</option><option value="volunteers">Volunteers</option><option value="participants">Quiz Participants</option></select></div><div class="col-md-3"><input name="subject" class="form-control" placeholder="Subject" required></div><div class="col-md-4"><input name="message" class="form-control" placeholder="Message" required></div><div class="col-md-2"><button class="btn btn-dark w-100">Queue Email</button></div></form><div class="table-responsive mt-2"><table class="table table-sm"><thead><tr><th>Subject</th><th>Target</th><th>Count</th><th>Status</th></tr></thead><tbody><?php foreach($emails as $m): ?><tr><td><?= e($m['subject']) ?></td><td><?= e($m['recipient_type']) ?></td><td><?= (int)$m['recipients_count'] ?></td><td><?= e($m['status']) ?></td></tr><?php endforeach; ?></tbody></table></div>

<h4 id="leaderboard" class="mt-4">Leaderboard (Top 10)</h4><?php foreach($leaderboard as $i=>$l): ?><div><?= $i+1 ?>. <?= e($l['participant_name']) ?> - <?= (int)$l['score'] ?></div><?php endforeach; ?>

<h4 id="media" class="mt-4">Seminars / Webinars / Media Upload</h4><form method="post" class="row g-2"><?= csrf_input() ?><input type="hidden" name="create_event" value="1"><div class="col-md-2"><select name="event_type" class="form-select"><option>Seminar</option><option>Webinar</option><option>News</option><option>Media</option></select></div><div class="col-md-3"><input name="title" class="form-control" required placeholder="Title"></div><div class="col-md-3"><input name="location" class="form-control" placeholder="Location"></div><div class="col-md-2"><input type="date" name="event_date" class="form-control" required></div><div class="col-md-2"><button class="btn btn-success w-100">Publish</button></div><div class="col-12"><textarea name="description" class="form-control" required></textarea></div></form>

<h4 id="settings" class="mt-4">Super Admin Settings</h4><div class="table-responsive mb-3"><table class="table table-striped"><thead><tr><th>Name</th><th>Email</th><th>Role</th></tr></thead><tbody><?php foreach($admins as $a): ?><tr><td><?= e($a['name']) ?></td><td><?= e($a['email']) ?></td><td><?= e($a['role']) ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php if(is_super_admin_logged_in()): ?><form method="post" class="row g-2"><?= csrf_input() ?><input type="hidden" name="create_admin" value="1"><div class="col-md-3"><input name="name" class="form-control" required placeholder="Admin name"></div><div class="col-md-3"><input name="email" class="form-control" type="email" required placeholder="Admin email"></div><div class="col-md-3"><input name="password" class="form-control" type="password" required placeholder="Password"></div><div class="col-md-2"><select name="role" class="form-select"><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select></div><div class="col-md-1"><button class="btn btn-dark w-100">Add</button></div></form><?php endif; ?>
</section></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
